matrix:
    os: linux
    dist: bionic
    arch: arm64-graviton2
    
    include:
        - language: cpp
          compiler: clang
          script:
            - g++ hello.cpp  
        - language: python
          script:
            - python hello.py
        - language: ruby
          rvm:
            - 2.5
          script:
            - ruby hello.rb
