os: linux
dist: bionic
arch: arm64-graviton2
jobs:
  include:
    - language: cpp
      compiler: clang
      script:
        - g++ hello.cpp -o travis_gcc_cpp98
        - ./travis_gcc_cpp98
    - language: python
      script:
        - python hello.py
    - language: ruby
      rvm:
        - 2.5
      script:
        - ruby hello.rb
