os: linux
dist: bionic
arch: arm64-graviton2
jobs:
  include:
    - language: cpp
      compiler: g++
      script:
        - clang++ hello.cpp
    - language: python
      script:
        - python hello.py
    - language: ruby
      rvm:
        - 2.5
      script:
        - ruby hello.rb
